/* Auto-generated by scan-assets.js — do not edit by hand */
/* Run: npm run scan   (also runs automatically with npm run dev / build) */
const ASSETS = {
  "images": [
    {
      "filename": "ChatGPT Image Aug 12, 2026, 09_06_07 AM.png",
      "url": "images/ChatGPT%20Image%20Aug%2012%2C%202026%2C%2009_06_07%20AM.png",
      "name": "ChatGPT Image Aug 12, 2026, 09 06 07 AM"
    },
    {
      "filename": "graphic1.png",
      "url": "images/graphic1.png",
      "name": "Graphic1"
    },
    {
      "filename": "graphic2.jpg",
      "url": "images/graphic2.jpg",
      "name": "Graphic2"
    },
    {
      "filename": "graphic3.jpg",
      "url": "images/graphic3.jpg",
      "name": "Graphic3"
    },
    {
      "filename": "graphic4.png",
      "url": "images/graphic4.png",
      "name": "Graphic4"
    }
  ],
  "videos": [
    {
      "filename": "edit 1.mp4",
      "url": "videos/edit%201.mp4",
      "name": "Edit 1",
      "poster": null
    },
    {
      "filename": "edit 2.mp4",
      "url": "videos/edit%202.mp4",
      "name": "Edit 2",
      "poster": null
    },
    {
      "filename": "edit 3.mp4",
      "url": "videos/edit%203.mp4",
      "name": "Edit 3",
      "poster": null
    },
    {
      "filename": "edit 4.mp4",
      "url": "videos/edit%204.mp4",
      "name": "Edit 4",
      "poster": null
    },
    {
      "filename": "WhatsApp Video 2026-07-26 at 13.37.09.mp4",
      "url": "videos/WhatsApp%20Video%202026-07-26%20at%2013.37.09.mp4",
      "name": "WhatsApp Video 2026 07 26 At 13.37.09",
      "poster": null
    }
  ],
  "models": [
    {
      "filename": "product-visual.jpg",
      "url": "3d-assets/product-visual.jpg",
      "name": "Product Visual",
      "type": "image"
    },
    {
      "filename": "purple-cube.gltf",
      "url": "3d-assets/purple-cube.gltf",
      "name": "Purple Cube",
      "type": "model"
    },
    {
      "filename": "sample-box.glb",
      "url": "3d-assets/sample-box.glb",
      "name": "Sample Box",
      "type": "model"
    },
    {
      "filename": "sample-duck.glb",
      "url": "3d-assets/sample-duck.glb",
      "name": "Sample Duck",
      "type": "model"
    },
    {
      "filename": "studio-render.png",
      "url": "3d-assets/studio-render.png",
      "name": "Studio Render",
      "type": "image"
    }
  ],
  "tools": [
    {
      "filename": "aftereffects.png",
      "url": "tools/aftereffects.png",
      "name": "Aftereffects"
    },
    {
      "filename": "animatecc.png",
      "url": "tools/animatecc.png",
      "name": "Animatecc"
    },
    {
      "filename": "canva.png",
      "url": "tools/canva.png",
      "name": "Canva"
    },
    {
      "filename": "illustrator.png",
      "url": "tools/illustrator.png",
      "name": "Illustrator"
    },
    {
      "filename": "maya.png",
      "url": "tools/maya.png",
      "name": "Maya"
    },
    {
      "filename": "photoshop.png",
      "url": "tools/photoshop.png",
      "name": "Photoshop"
    },
    {
      "filename": "premiere.png",
      "url": "tools/premiere.png",
      "name": "Premiere"
    }
  ],
  "profile": [
    {
      "filename": "priya-portrait.png",
      "url": "profile/priya-portrait.png",
      "name": "Priya Portrait"
    }
  ]
};

if (typeof window !== "undefined") {
  window.ASSETS = ASSETS;
}

export default ASSETS;
