const fs = require('fs');
const path = require('path');

const ROOT = __dirname;
const PUBLIC_DIR = path.join(ROOT, 'public');
const OUTPUT = path.join(ROOT, 'assets-data.js');

const IMAGE_EXTS = new Set(['.jpg', '.jpeg', '.png', '.webp', '.gif']);
const VIDEO_EXTS = new Set(['.mp4', '.webm', '.mov']);
const MODEL_EXTS = new Set(['.glb', '.gltf']);
const RENDER_EXTS = new Set(['.jpg', '.jpeg', '.png', '.webp']);
const TOOL_EXTS = new Set(['.png', '.jpg', '.jpeg', '.webp', '.svg']);
const PROFILE_EXTS = new Set(['.jpg', '.jpeg', '.png', '.webp', '.gif']);

function ensureDir(dirPath) {
  if (!fs.existsSync(dirPath)) {
    fs.mkdirSync(dirPath, { recursive: true });
  }
}

function cleanName(filename) {
  const base = path.parse(filename).name;
  return base
    .replace(/[_-]+/g, ' ')
    .replace(/\s+/g, ' ')
    .trim()
    .replace(/\b\w/g, (c) => c.toUpperCase());
}

function listFiles(dirPath, allowedExts) {
  ensureDir(dirPath);
  try {
    return fs
      .readdirSync(dirPath, { withFileTypes: true })
      .filter((entry) => entry.isFile())
      .map((entry) => entry.name)
      .filter((name) => allowedExts.has(path.extname(name).toLowerCase()))
      .sort((a, b) => a.localeCompare(b, undefined, { sensitivity: 'base' }));
  } catch {
    return [];
  }
}

function assetUrl(folder, filename) {
  // Vite serves files from /public at the site root
  return `${folder}/${encodeURIComponent(filename)}`;
}

function buildAssets() {
  ensureDir(path.join(PUBLIC_DIR, 'profile'));
  ensureDir(path.join(PUBLIC_DIR, 'images'));
  ensureDir(path.join(PUBLIC_DIR, 'videos'));
  ensureDir(path.join(PUBLIC_DIR, '3d-assets'));
  ensureDir(path.join(PUBLIC_DIR, 'tools'));

  const images = listFiles(path.join(PUBLIC_DIR, 'images'), IMAGE_EXTS).map(
    (filename) => ({
      filename,
      url: assetUrl('images', filename),
      name: cleanName(filename),
    })
  );

  const videosDir = path.join(PUBLIC_DIR, 'videos');
  const videos = listFiles(videosDir, VIDEO_EXTS).map((filename) => {
    const base = path.parse(filename).name;
    const posterCandidates = ['.jpg', '.jpeg', '.png', '.webp'].map(
      (ext) => `${base}${ext}`
    );
    const posterFile = posterCandidates.find((candidate) =>
      fs.existsSync(path.join(videosDir, candidate))
    );

    return {
      filename,
      url: assetUrl('videos', filename),
      name: cleanName(filename),
      poster: posterFile ? assetUrl('videos', posterFile) : null,
    };
  });

  const models = listFiles(
    path.join(PUBLIC_DIR, '3d-assets'),
    new Set([...MODEL_EXTS, ...RENDER_EXTS])
  ).map((filename) => {
    const ext = path.extname(filename).toLowerCase();
    return {
      filename,
      url: assetUrl('3d-assets', filename),
      name: cleanName(filename),
      type: MODEL_EXTS.has(ext) ? 'model' : 'image',
    };
  });

  const tools = listFiles(path.join(PUBLIC_DIR, 'tools'), TOOL_EXTS).map(
    (filename) => ({
      filename,
      url: assetUrl('tools', filename),
      name: cleanName(filename),
    })
  );

  const profile = listFiles(path.join(PUBLIC_DIR, 'profile'), PROFILE_EXTS).map(
    (filename) => ({
      filename,
      url: assetUrl('profile', filename),
      name: cleanName(filename),
    })
  );

  return { images, videos, models, tools, profile };
}

function writeAssetsFile(assets) {
  const contents = `/* Auto-generated by scan-assets.js — do not edit by hand */
/* Run: npm run scan   (also runs automatically with npm run dev / build) */
const ASSETS = ${JSON.stringify(assets, null, 2)};

if (typeof window !== "undefined") {
  window.ASSETS = ASSETS;
}

export default ASSETS;
`;
  fs.writeFileSync(OUTPUT, contents, 'utf8');
  return assets;
}

function scanAndWrite() {
  const assets = writeAssetsFile(buildAssets());
  console.log(
    `Assets scanned → assets-data.js (${assets.images.length} images, ${assets.videos.length} videos, ${assets.models.length} 3d, ${assets.tools.length} tools, ${assets.profile.length} profile)`
  );
  return assets;
}

module.exports = {
  buildAssets,
  scanAndWrite,
  listFiles,
  cleanName,
  assetUrl,
  PUBLIC_DIR,
  IMAGE_EXTS,
  VIDEO_EXTS,
  MODEL_EXTS,
  RENDER_EXTS,
  TOOL_EXTS,
  PROFILE_EXTS,
};

if (require.main === module) {
  scanAndWrite();
}
